name: derp code sync 

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ROM on Self-hosted
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Initialize Repo
        run: |
          wget https://raw.githubusercontent.com/akhilnarang/scripts/refs/heads/master/setup/android_build_env.sh
          chmod u+x android_build_env.sh
          ./android_build_env.sh
          git clone https://github.com/Fake-suns/local_manifests.git -b main .repo/local_manifests
          repo sync --force-sync -j14 --current-branch --no-tags --no-clone-bundle --optimized-fetch --force-broken
